version: '3.9'

services:
  #Base de donnée
  mariadb:
    name: mariadb
    build: ./requirements/mariadb
    volumes:
      -mariadb_v:/var/lib/mysql
    environment:
      - .env
    network:
      -inception
    restart: always

  #Plateforme site web
  wordpress:
    name: wordpress
    build: ./requirements/wordpress
    volumes: 
      - wordpress_v:/var/www/html
    depends_on:
      -mariadb
    environment:
      - .env
    network:
      - inception
    restart: always

  #Server Web. Utilise http pour afficher un site web
  nginx:
    name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_v:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    environment:
      - .env
    network:
      - inception
    restart: always

networks:
  inception:
    driver: bridge #Default network driver. Connects the linked containers so they can communicate together. Aslo isolate them from other containers, not ont hat network.

volumes:
 mariadb_v:
    driver: local 
    driver_opts: #driver options
      type: none
      o: bind #mount option: bind mount est utilisé lorsque le docker est dépendant d'un répertoire de l'hôte, surtout utilisé s'il y a des fichiers de configuration. Pratique lorsque l'on doit modifier ou accéder un ou des fichiers
      device: /home/anhebert/data/mariadb
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      o: bind #mount option
      device: /home/anhebert/data/wordpress

